FROM python:3.10-slim

WORKDIR /app

# Copy only requirements for cache
COPY requirements.txt .

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    ffmpeg \
    git \
    libgl1-mesa-glx \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir -r requirements.txt

# Copy app code last
COPY . .
COPY ./NeMo /root/.cache/torch/NeMo

CMD ["celery", "-A", "worker.app", "worker", "--loglevel=info"]
